# Tomcat
server:
  port: 8060
  servlet:
    context-path: /

# Spring
spring:
  application:
    # 应用名称
    name: service-order
    #  profiles:
    # 环境配置
  #    active: @profiles.active@
  # Nacos帮助文档: https://nacos.io/zh-cn/docs/concepts.html
  # Nacos认证信息
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 127.0.0.1:8848
        # 注册到 nacos 的指定 namespace，默认为 public
        namespace: public

# openfeign配置包下（或指定哪些业务接口）以什么日志级别监听，springboot的默认日志级别是info，openFeign的日志级别debug就不会输出，所以需要加上此配置
logging:
  level:
    com.ablaze.serviceopenfeign.openfeign: debug
#logging.level.com.ablaze.serviceopenfeign.openfeign.StockOpenFeignService=debug