# Tomcat
server:
  port: 8040
  servlet:
    context-path: /

# Spring
spring:
  application:
    # 应用名称
    name: service-order
    #  profiles:
    # 环境配置
  #    active: @profiles.active@
  # Nacos帮助文档: https://nacos.io/zh-cn/docs/concepts.html
  # Nacos认证信息
  cloud:
    nacos:
      discovery:
        username: nacos
        password: nacos
        server-addr: 127.0.0.1:8848
        # 注册到 nacos 的指定 namespace，默认为 public
        namespace: public
    #不使用ribbon
#    loadbalancer:
#      ribbon:
#        enabled: false

#方式2：负载均衡配置文件
#指定使用Nacos提供的负载均衡策略（优先调用同一集群实例，基于随机和权重）
#service-stock.ribbon.NFLoadBalancerRuleClassName=com.alibaba.cloud.nacos.ribbon.NacosRule
#指定自定义负载均衡策略规则CustomRule类，使用自己定义的规则
#service-stock.ribbon.NFLoadBalancerRuleClassName=com.qt.ribbon.rule.CustomRule